version: '3'
services:
  stable:
    environment:
      - UID=${HOST_UID:-0}
      - GID=${HOST_GID:-0}
      - USER=${HOST_USER:-root}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
      - BUILD_ROOTDIR=/git/.build
    build:
      context: stable
    volumes:
    - ${WORKDIR}:/git:rw
  devel:
    environment:
      - UID=${HOST_UID:-0}
      - GID=${HOST_GID:-0}
      - USER=${HOST_USER:-root}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
      - BUILD_ROOTDIR=/git/.build
    build:
      context: devel
    volumes:
    - ${WORKDIR}:/git:rw
